### ISSUE TITLE
Need ideas on how to proceed with project

### ISSUE THREAD

**Issue by gowtham-prudhvi** [CS252-2016-GROUP-46/coursebucket#1]

**Comment by krishnakarthik1309** [comment]
Today prof announced in class that this thursday in class there will be individual group discussion with prof/TA about our project. So tomorrow we should sit together and decide. Is that okay or any other time before thursday?

**Comment by gowtham-prudhvi** [comment]
Tomorrow may be after your CS300 presentation?

**Comment by krishnakarthik1309** [comment]
Its 10-12 right :( In the evening? or you mean in class after my presentation.. okay :+1:

**Comment by gowtham-prudhvi** [comment]
Either at 12 or at around 3:30  fix one and stick to it
